export enum OrderStatus {
  AWITING_PAYMENT = 'AWITING_PAYMENT',
  AWITING_DELIVERY = 'AWITING_DELIVERY',
  AWITING_RECEIVING = 'AWITING_RECEIVING',
  AWITING_RETURN = 'AWITING_RETURN',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  INT_PROCESS = 'INT_PROCESS',
}
